fixtures:
  symlinks:
    threatstack: "#{source_dir}"
  repositories:
    simp_grub: "https://github.com/simp/pupmod-simp-simp_grub"
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    apt: "puppetlabs/apt"
    translate: "puppetlabs/translate"
    auditd: "simp/auditd"
    archive: "puppet/archive"
    remote_file: "lwf/remote_file"
    concat: "puppetlabs/concat"
    simplib: "simp/simplib"
