language: ruby
before_install:
  - gem install bundler
  - sudo apt-get install -y lsb-release
bundler_args: "--without system_tests"
script: bundle install && bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'
cache: bundler
sudo: required
rvm:
- 2.3.1
- 2.4.1
- 2.5.1
- 2.6.0
env:
- PUPPET_VERSION="~> 5.5.8"
